name: Test-Program Development

# Triggers the workflow on push or pull request events for all branches
on: [push, pull_request]

jobs:
  
  build:
    # This job runs for the push and pull_request events triggered on feature branches
    if: ${{ github.ref != 'refs/heads/main' && github.event_name == 'pull_request'}}
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: sudo apt-get install build-essential
      - name: Build
        run: make
      - name: Run The Test
        run: make check
      - name: Upload The Program
        uses: actions/upload-artifact@v2.2.3
        with:
          name: program
          path: bin/test

  deploy:
    # This job runs only for the push events triggered on the main branch
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    name: make-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: |
          sudo apt-get install zip
          sudo apt-get install build-essential
      - name: Build
        run: |
          make
          cd bin
          zip program.zip test
      - name: Run The Test
        run: make check
      - name: Upload The Program
        uses: actions/upload-artifact@v2.2.3
        with:
          name: program
          path: bin/test  
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Version
          files: bin/program.zip
